"""Scientific family -> the label a player sees on the family clue chip.

"Accipitridae" is useless as a clue, so every family in the pool needs a name
an ordinary person would recognise. Rules used here:

* Short enough for a chip: one or two words wherever possible.
* Grouped the way a player thinks, not the way a taxonomist does. Barn owls
  and true owls are both "Owls"; the three parrot families are all "Parrots";
  New and Old World sparrows are all "Sparrows". A guesser who tries a vulture
  expects it to match another vulture.
* Families with no recognisable common label are simply left out. Their
  species drop from the pool rather than shipping a chip nobody can read;
  build_rows() reports what was dropped so gaps can be filled deliberately.
"""

FAMILY_LABELS: dict[str, str] = {
    # --- raptors and vultures ---
    "Accipitridae": "Hawks & Eagles",
    "Pandionidae": "Osprey",
    "Falconidae": "Falcons",
    "Cathartidae": "Vultures",
    "Sagittariidae": "Secretarybird",
    "Cariamidae": "Seriemas",
    # --- owls ---
    "Strigidae": "Owls",
    "Tytonidae": "Owls",
    # --- gamebirds ---
    "Phasianidae": "Pheasants",
    "Odontophoridae": "Quails",
    "Numididae": "Guineafowl",
    "Cracidae": "Curassows",
    "Megapodiidae": "Megapodes",
    "Tinamidae": "Tinamous",
    # --- ratites ---
    "Struthionidae": "Ostriches",
    "Rheidae": "Rheas",
    # AVONET files the emu here with the cassowaries. Taxonomically fine, but
    # a chip reading "Cassowaries" under Emu is not.
    "Casuariidae": "Emu & Cassowaries",
    "Dromaiidae": "Emu",
    "Apterygidae": "Kiwis",
    # --- waterfowl and waterbirds ---
    "Anatidae": "Waterfowl",
    "Anhimidae": "Screamers",
    "Anseranatidae": "Magpie Goose",
    "Podicipedidae": "Grebes",
    "Gaviidae": "Loons",
    "Phoenicopteridae": "Flamingos",
    # --- herons, storks and allies ---
    "Ardeidae": "Herons",
    "Ciconiidae": "Storks",
    "Threskiornithidae": "Ibises",
    "Balaenicipitidae": "Shoebill",
    "Scopidae": "Hamerkop",
    "Pelecanidae": "Pelicans",
    "Phalacrocoracidae": "Cormorants",
    "Anhingidae": "Darters",
    # --- seabirds ---
    "Spheniscidae": "Penguins",
    "Diomedeidae": "Albatrosses",
    "Procellariidae": "Petrels",
    "Hydrobatidae": "Storm Petrels",
    "Oceanitidae": "Storm Petrels",
    "Pelecanoididae": "Diving Petrels",
    "Sulidae": "Gannets",
    "Fregatidae": "Frigatebirds",
    "Phaethontidae": "Tropicbirds",
    "Laridae": "Gulls & Terns",
    "Stercorariidae": "Skuas",
    "Alcidae": "Auks",
    # --- shorebirds ---
    "Scolopacidae": "Sandpipers",
    "Charadriidae": "Plovers",
    "Haematopodidae": "Oystercatchers",
    "Recurvirostridae": "Avocets",
    "Burhinidae": "Thick-knees",
    "Jacanidae": "Jacanas",
    "Glareolidae": "Pratincoles",
    "Rostratulidae": "Painted-snipes",
    "Chionidae": "Sheathbills",
    "Dromadidae": "Crab-plover",
    "Ibidorhynchidae": "Ibisbill",
    "Thinocoridae": "Seedsnipes",
    "Turnicidae": "Buttonquails",
    # --- cranes, rails and allies ---
    "Gruidae": "Cranes",
    "Rallidae": "Rails & Crakes",
    "Aramidae": "Limpkin",
    "Psophiidae": "Trumpeters",
    "Heliornithidae": "Finfoots",
    "Otididae": "Bustards",
    "Eurypygidae": "Sunbittern",
    "Rhynochetidae": "Kagu",
    "Mesitornithidae": "Mesites",
    # --- pigeons, sandgrouse, cuckoos, turacos ---
    "Columbidae": "Pigeons",
    "Pteroclidae": "Sandgrouse",
    "Cuculidae": "Cuckoos",
    "Musophagidae": "Turacos",
    "Opisthocomidae": "Hoatzin",
    # --- nightbirds ---
    "Caprimulgidae": "Nightjars",
    "Podargidae": "Frogmouths",
    "Nyctibiidae": "Potoos",
    "Steatornithidae": "Oilbird",
    "Aegothelidae": "Owlet-nightjars",
    # --- swifts and hummingbirds ---
    "Apodidae": "Swifts",
    "Hemiprocnidae": "Treeswifts",
    "Trochilidae": "Hummingbirds",
    # --- trogons, kingfishers and allies ---
    "Trogonidae": "Trogons",
    "Coliidae": "Mousebirds",
    "Leptosomidae": "Cuckoo-roller",
    "Alcedinidae": "Kingfishers",
    "Todidae": "Todies",
    "Momotidae": "Motmots",
    "Meropidae": "Bee-eaters",
    "Coraciidae": "Rollers",
    "Brachypteraciidae": "Ground Rollers",
    "Upupidae": "Hoopoes",
    "Phoeniculidae": "Wood Hoopoes",
    "Bucerotidae": "Hornbills",
    "Bucorvidae": "Ground Hornbills",
    # --- woodpeckers and allies ---
    "Picidae": "Woodpeckers",
    "Ramphastidae": "Toucans",
    "Capitonidae": "Barbets",
    "Megalaimidae": "Barbets",
    "Lybiidae": "Barbets",
    "Semnornithidae": "Barbets",
    "Galbulidae": "Jacamars",
    "Bucconidae": "Puffbirds",
    "Indicatoridae": "Honeyguides",
    # --- parrots ---
    "Psittacidae": "Parrots",
    "Psittaculidae": "Parrots",
    "Strigopidae": "Parrots",
    "Cacatuidae": "Cockatoos",
    # --- suboscine passerines ---
    "Furnariidae": "Ovenbirds",
    "Dendrocolaptidae": "Woodcreepers",
    "Scleruridae": "Leaftossers",
    "Thamnophilidae": "Antbirds",
    "Formicariidae": "Antthrushes",
    "Grallariidae": "Antpittas",
    "Rhinocryptidae": "Tapaculos",
    "Conopophagidae": "Gnateaters",
    "Tyrannidae": "Flycatchers",
    "Pipridae": "Manakins",
    "Cotingidae": "Cotingas",
    "Tityridae": "Tityras",
    "Pittidae": "Pittas",
    "Eurylaimidae": "Broadbills",
    "Calyptomenidae": "Broadbills",
    "Acanthisittidae": "New Zealand Wrens",
    # --- Australasian passerines ---
    "Menuridae": "Lyrebirds",
    "Ptilonorhynchidae": "Bowerbirds",
    "Climacteridae": "Treecreepers",
    "Maluridae": "Fairywrens",
    "Meliphagidae": "Honeyeaters",
    "Pardalotidae": "Pardalotes",
    "Acanthizidae": "Thornbills",
    "Pomatostomidae": "Babblers",
    "Petroicidae": "Australasian Robins",
    "Paradisaeidae": "Birds-of-paradise",
    "Callaeidae": "Wattlebirds",
    "Artamidae": "Butcherbirds",
    "Cracticidae": "Butcherbirds",
    "Neosittidae": "Sittellas",
    "Psophodidae": "Whipbirds",
    "Pachycephalidae": "Whistlers",
    "Rhipiduridae": "Fantails",
    "Monarchidae": "Monarchs",
    "Grallinidae": "Mudnesters",
    "Corcoracidae": "Mudnesters",
    "Oreoicidae": "Bellbirds",
    "Mohouidae": "Whiteheads",
    "Notiomystidae": "Stitchbird",
    # --- crows, shrikes and allies ---
    "Corvidae": "Crows & Jays",
    "Laniidae": "Shrikes",
    "Vireonidae": "Vireos",
    "Oriolidae": "Orioles",
    "Dicruridae": "Drongos",
    "Campephagidae": "Cuckooshrikes",
    "Malaconotidae": "Bushshrikes",
    "Platysteiridae": "Wattle-eyes",
    "Vangidae": "Vangas",
    "Prionopidae": "Helmetshrikes",
    "Aegithinidae": "Ioras",
    "Picathartidae": "Rockfowl",
    # --- thrushes, chats, starlings ---
    "Turdidae": "Thrushes",
    "Muscicapidae": "Chats",
    "Cinclidae": "Dippers",
    "Sturnidae": "Starlings",
    "Buphagidae": "Oxpeckers",
    "Mimidae": "Mockingbirds",
    "Bombycillidae": "Waxwings",
    "Ptiliogonatidae": "Silky-flycatchers",
    # --- tits, swallows, warblers ---
    "Paridae": "Tits",
    "Remizidae": "Penduline Tits",
    "Aegithalidae": "Long-tailed Tits",
    "Hirundinidae": "Swallows",
    "Alaudidae": "Larks",
    "Panuridae": "Bearded Reedling",
    "Pycnonotidae": "Bulbuls",
    # Every one of these reads as "a warbler" to a player; splitting them into
    # six families would make the clue meaningless.
    "Parulidae": "Warblers",
    "Acrocephalidae": "Warblers",
    "Phylloscopidae": "Warblers",
    "Sylviidae": "Warblers",
    "Cisticolidae": "Warblers",
    "Locustellidae": "Warblers",
    "Scotocercidae": "Warblers",
    "Macrosphenidae": "Warblers",
    "Icteriidae": "Warblers",
    # --- babblers, white-eyes and allies ---
    "Timaliidae": "Babblers",
    "Pellorneidae": "Babblers",
    "Leiotrichidae": "Laughingthrushes",
    "Zosteropidae": "White-eyes",
    "Paradoxornithidae": "Parrotbills",
    "Regulidae": "Kinglets",
    # --- nuthatches, wrens, gnatcatchers ---
    "Sittidae": "Nuthatches",
    "Tichodromadidae": "Wallcreeper",
    "Certhiidae": "Treecreepers",
    "Polioptilidae": "Gnatcatchers",
    "Troglodytidae": "Wrens",
    # --- sunbirds, flowerpeckers, leafbirds ---
    "Nectariniidae": "Sunbirds",
    "Dicaeidae": "Flowerpeckers",
    "Chloropseidae": "Leafbirds",
    "Irenidae": "Fairy-bluebirds",
    "Promeropidae": "Sugarbirds",
    # --- finches, sparrows, buntings, tanagers ---
    "Fringillidae": "Finches",
    "Passeridae": "Sparrows",
    "Passerellidae": "Sparrows",
    "Ploceidae": "Weavers",
    "Estrildidae": "Waxbills",
    "Viduidae": "Whydahs",
    "Prunellidae": "Accentors",
    "Motacillidae": "Wagtails",
    "Emberizidae": "Buntings",
    "Calcariidae": "Longspurs",
    "Cardinalidae": "Cardinals",
    "Thraupidae": "Tanagers",
    "Icteridae": "Blackbirds",
    "Peucedramidae": "Olive Warbler",
}
